### ISSUE TITLE
Info api fails

### ISSUE THREAD

**Issue by rcollette** [joeferner/redis-commander#291]
I have a valid bastion/jump host configured that I am using to connect to an AWS Elasticache Redis instance.   I can connect to that instance on client A, using redis-cli, and I can execute commands like info from client A, using the default Redis port number.

Also on client A, I start up redis-commander, having tried both the default 127.0.0.0 host as well as 127.0.0.1  In both cases I see on the console 
```
No Save: true
listening on  0.0.0.0 : 8081
Redis Connection 127.0.0.1:6379 Using Redis DB #0
```

When I open the redis-commander application in a browser,  the HTML page loads,  I can see a call to the /info endpoint being made.  That /info request fails with no HTTP response code and there are no errors in the console that is running the redis-commander host.

Is there a way to debug this further?   Any known issues with this use case? I searched the issues and couldn't find anything similar.

**Comment by RafaAguilar** [comment]
The same scenario has happened to our team lately, but from Docker latest image.

Using manual installation from the same Docker Host, it runs flawlessly.

**Comment by baileymiller182** [comment]
👍 Something is definitely broken with the docker latest image. New containers of redis-commander:latest isn't loading nodes into the DOM.

**Comment by sseide** [comment]
redis commander had a problem when one of the redis servers was not accessible - the serverInfo request did not return at all then.
Problem with latest image was created by CR #326 that added a implicit connection to localhost for most users - and if there is no redis server running it hangs..

fixed with #330, should be more robust now. And reverted #326 along the way...

**Comment by sseide** [comment]
Can all of you retest with latest docker image? If there some errors we may be able to fix it then...

**Comment by RafaAguilar** [comment]
Latest Docker Image working flawlessly, Thanks @sseide !

**Comment by rcollette** [comment]
It's not clear if the npm distribution was updated or not.  I installed with npm  and mine crashed with

```
Using default configuration.
/Users/richardcollette/.nvm/versions/node/v8.11.3/lib/node_modules/redis-commander/lib/routes/home.js:40
      reducedConfig.default_connections.forEach(function(item) {
                                        ^

TypeError: Cannot read property 'forEach' of undefined
    at /Users/richardcollette/.nvm/versions/node/v8.11.3/lib/node_modules/redis-commander/lib/routes/home.js:40:41
    at ReadFileContext.callback (/Users/richardcollette/.nvm/versions/node/v8.11.3/lib/node_modules/redis-commander/lib/util.js:130:7)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

**Comment by rcollette** [comment]
I ran
```
docker run --rm --name redis-commander -d -p 8081:8081 rediscommander/redis-commander:latest
```

And I still get no response from the /info endpoint.  Spinner just keeps going on the redis server tree node in the UI.

**Comment by sseide** [comment]
HI,

npm is not updated right now. This must be done manually be Joe Ferner. Its not automatic as docker image build...

Running with latest docker image - Spinning wheel happens when the first connection in the tree is not working. Then this one hangs. Was only able to fix it completly for all other connections from the second on not preselected automatically. But /info call should return with error message (looking at raw request with Browser debug/network tools),

That happens because UI tries to fetch keys for first connection, and, as redis connection is not working, it hangs... So the root cause seems to be redis commander (or ioredis lib) not able to connect to redis server.

Do you see a line `Redis Connection 127.0.0.1:6379 Using Redis DB #0` for your first connection?

**Comment by rcollette** [comment]
So this worked 

```
US-RI026CO-MLT:~ richardcollette$ docker run --rm --name redis-commander -p 8081:8081 --env REDIS_HOST=host.docker.internal rediscommander/redis-commander:latest 
Creating custom redis-commander config '/redis-commander/config/local-production.json'.
node ./bin/redis-commander --redis-host host.docker.internal
No Save: false
listening on  0.0.0.0 : 8081
Redis Connection host.docker.internal:6379 Using Redis DB #0
```

Tried adding a key with the right pane button from the root node but the key for the added value becomes 'undefined'.   I was able to set and get a key from the console portion of the application.  (All a separate issue).
